### ISSUE TITLE
switching to action set by number

### ISSUE THREAD

**Issue by charlierudolph** [kevgo/tertestrial#57]
I never liked this API and still dislike this as its dependent on the order of keys in an object. I'd either like it to be removed or changed in some way where you label an action set with a number or something.

@kevgo thoughts?

**Comment by kevgo** [comment]
The config used to be an array (with proper sorting) until you made it an object in https://github.com/Originate/tertestrial-server/commit/5c4ed786c6e6c2060ea427b51076fff1064ee1b0. Assigning numeric keys to the object could work here. The advantage is that people can assign any number to it. The disadvantage is that its a bit more manual with the possibility for error. I don't feel strongly either way, and am fine with anything as long as I can switch action sets by number.

**Comment by kevgo** [comment]
Going back to an array for action sets in the new configuration format.
